config/routes.rb
Pops::Application.routes.draw do

  root 'orders#index'
  
  controller :welcome do
    get 'welcome' => :index
  end
  
  controller :sessions do
    get  'login'  => :new
    post 'login'  => :create
    get  'logout' => :destroy
  end
  
  get  'tbr'                 => 'tbr#select'
  get  'tbr/select'          => 'tbr#select'
  get  'tbr/reports'         => 'tbr#reports'
  post 'tbr/report'          => 'tbr#report'
  post 'tbr/go'              => 'tbr#go'
  get  'tbr/log/:id'         => 'tbr#log'
  post 'tbr/log/:id'         => 'tbr#log'
  
  resources :accounts,      :except => [:create, :delete, :show]
  resources :payment_terms, :except => [:create, :delete, :show]
  resources :programs,      :except => [:create, :delete, :show]    
  resources :suppliers,     :except => [:create, :delete, :show]
  resources :tax_rates,     :except => [:create, :delete, :show]
  resources :users
  resources :deliveries
  resources :tbr_services
  
  get  'notes'               => 'notes#index'
  
  get  'orders/refresh'      => 'orders#refresh'
  get  'orders/:id/print'    => 'orders#print' 
  get  'orders/:id/search'   => 'orders#search'
  
  resources :orders do
    resources :items,    :only => [:new]
  end 
  
  post  'orders/refresh'       => 'orders#refresh'
  patch 'orders/:id/redraft'   => 'orders#redraft'
  post  'orders/:id/submit'    => 'orders#submit'
  patch 'orders/:id/resubmit'  => 'orders#resubmit'
  post  'orders/:id/approve'   => 'orders#approve'
  patch 'orders/:id/reapprove' => 'orders#reapprove'
  patch 'orders/:id/complete'  => 'orders#complete'
  
  resources :items,    :except => [:index, :new] 
  resources :receipts, :only   => [:create, :new]
  
  
  post  'orders/:id/items/gst'  => 'items#gst'
  post  'items/:id/gst'         => 'items#gst'
  patch 'items/:id/gst'         => 'items#gst'
  post  'items/gst'             => 'items#gst'
  
  post  'orders/:id/items/tax_rate' => 'items#tax_rate'
  post  'items/:id/tax_rate'        => 'items#tax_rate'
  patch 'items/:id/tax_rate'        => 'items#tax_rate'
  post  'items/tax_rate'            => 'items#tax_rate'
  
  post  'orders/:id/items/account_select'  => 'items#account_select'
  post  'items/:id/account_select'         => 'items#account_select'
  patch 'items/:id/account_select'         => 'items#account_select'
  post  'items/account_select'             => 'items#account_select'
  
  post  'orders/:id/items/program_select'  => 'items#program_select'
  post  'items/:id/program_select'         => 'items#program_select'
  patch 'items/:id/program_select'         => 'items#program_select'
  post  'items/program_select'             => 'items#program_select'
  
  post  'orders/payment_date'     => 'orders#payment_date'
  patch 'orders/:id/payment_date' => 'orders#payment_date'
  
  post  'orders/delivery'         => 'orders#delivery'
  patch 'orders/:id/delivery'     => 'orders#delivery'
  
  post  'users/ldap'              => 'users#ldap'
  patch 'users/:id/ldap'          => 'users#ldap'
  
  post  'tbr/report_select'       => 'tbr#report_select'
  

  

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :order 
  belongs_to :user
  
  attr_reader :date_from, :date_to
  
  default_scope { order('created_at DESC') }
  
  validates :order_id,
            :user_id,
            :info,
            presence: true
  
  def self.by_order(order_id)
    where("order_id = ?", order_id)
  end
  
  def self.by_user(user_id)
    where("user_id = ?", user_id)
  end
  
  def self.by_info(info)
    where("info like ?", "%#{info}%")
  end
  
  def self.by_date(from,to)
    from_datetime = from.empty? ? '1/1/2000'.to_datetime : from.to_datetime
    to_datetime = to.empty? ? DateTime.now : to.to_datetime
    where(created_at: from_datetime.beginning_of_day..to_datetime.end_of_day)
  end
  
  def date_from=(date)
    @date_from = parse_date(:date_from,date)
  end
  
  def date_to=(date)
    @date_to = parse_date(:date_to,date)
  end        
    
  def user_name
    self.user ? self.user.name : "Missing User #{self.user_id}"
  end
  
  def formatted_date
    "#{self.created_at.strftime('%d/%m/%Y')} - #{self.created_at.strftime('%H:%M')}"
  end
  
  private
  
  def parse_date(id,date)
    return '' if date.nil? || date.empty?
    
    components = date.split(/\/|-/)
    components.map! { |c| c = c.to_i }
    
    components.each do |c|
      if c == 0
        self.errors.add(id,"contains invalid character - #{date}.  Valid formats include: d/m/yy, d/m and yyyy")
        return ''
      end
    end
    
    case components.size
      when 1
        d = 1
        m = 1
        year = components[0]
      when 2
        d = components[0]
        m = components[1]
        year = Date.today.year
      else
        d = components[0]
        m = components[1]
        year = components[2]
    end
    
    next_year = Date.today.year - 1999
    case year
      when (0..next_year)
        y = year + 2000
      when (next_year..2000)
        self.errors.add(id,"contains invalid year - #{year}  Valid formats include: d/m/yy, d/m and yyyy")
        return ''
      else
        y = year
    end
    
    begin
      parsed_date = Date.new(y,m,d) # catch exception and add error
    rescue ArgumentError
      self.errors.add(id,"is an invalid date format - #{date}.  Valid formats include: d/m/yy, d/m and yyyy")
      return '' 
    end
    
    parsed_date.strftime('%d/%m/%Y')
  end  
end

app/controllers/concerns/notes_helper.rb
module NotesHelper
  
  def save_json(name,model)
    name = name.downcase
    key = "#{name}_changes".to_sym
    model ? session[key] = model.to_json : session.delete(key)
  end
  
  def add_notes(name,model)
    name = name.downcase
    key = "#{name}_changes".to_sym
    if name == 'order'
      order_id = model ? model.id : session[key]['id']
    else
      order_id = model ? model.order_id : session[key]['order_id']
    end
    
    order = Order.find(order_id)
    if order.add_notes?
      diff = diff_model(key,model)
      if !diff.empty?
        if model.nil?
          action = 'deleted'
        elsif session[key].nil? || session[key].empty?
          action = 'added'
        else
          action = 'changed'
        end
        
        save_notes(order_id,"#{name.capitalize} #{action}:\n #{diff}")
      end
    end
    session.delete(key)
  end
  
  def save_user_notes(params)
    return if params[:order_notes].nil?
    save_notes(params[:id],params[:order_notes])
  end
  
  def save_notes(order_id,notes)
    note = Note.new
    note.order_id = order_id
    note.user_id = session[:user_id]
    note.info = notes
    note.save
  end
  
  def diff_model(key,model)
    from = session[key] || {}
    to = model ? model.to_json : {}
    from.delete_if { |key,value| key =~ /id$/ }
    to.delete_if { |key,value| key =~ /id$/ }   
    diff = ''
    
    if from.empty?
      to.each   { |key,value| diff << "- #{key}: #{val_format(value)}\n" }
    elsif to.empty?
      from.each { |key,value| diff << "- #{key}: #{val_format(value)}\n" }
    else
      from.each { |key,value| diff << "- #{key}: #{val_format(value)} to #{val_format(to[key])}\n" if from[key] != to[key] }
    end
    
    diff
  end
  
  private 
  
  def val_format(value)
    rval = "#{value}"
    rval.empty? ? '{empty}' : "\"#{rval}\""
  end
  
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  
  # GET /notes
  def index
    if params[:note]
      @note = Note.new(note_params)    
      @notes = Note.where(nil)
      @notes = @notes.by_order(@note.order_id) if @note.order_id
      @notes = @notes.by_user(@note.user_id) if @note.user_id
      @notes = @notes.by_info(@note.info) unless @note.info.empty?
      @notes = @notes.by_date(@note.date_from,@note.date_to) unless @note.date_from.empty? && @note.date_to.empty?
      @notes = @notes.paginate(page: params[:page], per_page: 10) 
    
      flash.alert = "No records found" if @notes.empty?
    else
      @notes = Note.none
      @note = Note.new
    end
  end
  
  private
  
  def note_params
    params.require(:note).permit(
      :order_id,
      :user_id,
      :info,
      :updated_at,
      :date_from,
      :date_to,
      :page)
  end

end

app/views/notes/index.html.erb
<div class=admin_form>

	<% flash.each do |name, msg| %>
		<%= content_tag :p, msg, class: name %>
	<% end %>
  
<%= form_for(@note, method: :get ) do |f| %>
      
    <% if @note.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@note.errors.count, "error") %> prohibited this search:</h2>
        <ul>
          <% @note.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class=header>
      <div class="header-title header-cells">Notes</div>
    </div>
      
    <div class="itemlist">
      <table width="100%">
        <th>Order</th>
        <th>Date</th>
        <th>User</th>
        <th>Info</th>
        <th></th>
        <tr class="search_row">
          <td><%= f.text_field :order_id, size: 5, class: "search_fields" %></td>
          <td><%= f.text_field :date_from, size: 9, class: "search_fields" %> to <%= f.text_field :date_to, size: 9, class: "search_fields" %></td>
          <td><%= f.select :user_id, User.users, { include_blank: true },
              { class: "btn btn-primary btn-md search_fields" } %></td>
          <td><%= f.text_field :info, class: "search_fields" %></td>
          <td align="right">
            <%= f.submit 'Search', class: "btn btn-primary btn-sm search_fields" %>
            <%= link_to 'Clear', notes_path, class: "btn btn-primary btn-sm search_fields" %>
          </td>
        </tr>
        <% @notes.each do |note| %>
          <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
            <td><%= link_to(note.order_id, order_path(note.order_id), class: "link_hilight") %></td>
            <td><%= note.formatted_date %></td>
    				<td><%= note.user_name %></td>
    				<td colspan="2"><%= html_newlines(note.info) %></td>
          </tr>
        <% end %>
      </table>
     
      <% flash.each do |name, msg| -%>
        <%= content_tag :p, msg, class: name %>
      <% end %>
      
      <% unless @notes.empty? %>
        <div class="digg_pagination">
          <div class="page_info">
            <%= page_entries_info @notes %>
          </div>
          <%= will_paginate @notes, :container => false %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>